// UI_React/src/app/pages/AddRecordPage/AddRecordPage.tsx
import { useContext, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { routesPaths } from '../routes';
import Area from '../../components/Area';
import Button from '../../components/Button';
import TextInput from '../../components/TextInput';
import { IFinanceRecord } from '../../api';
import { FinanceDataContext } from '../../contexts';

import './AddRecordPage.css';

export const AddRecordPage: React.FC = () => {
    const [description, setDescription] = useState<string>('');
    const [amount, setAmount] = useState<number>(0);
    const [date, setDate] = useState<string>(new Date().toISOString().split('T')[0]);

    const { addFinanceRecord } = useContext(FinanceDataContext);
    const navigate = useNavigate();

    const onAmountChange = (value: string) => {
        const numValue = parseInt(value);
        if (numValue) {
            setAmount(numValue);
        }
    };

    const onSubmitHandler = async (event: React.FormEvent) => {
        event.preventDefault();

        const newFinanceRecord: IFinanceRecord = {
            id: crypto.randomUUID(),
            date: new Date(date),
            amount,
            description,
        };

        await addFinanceRecord(newFinanceRecord);
        navigate(routesPaths.main);
    };

    const headerContent = (
        <div className='add-record-page__header'>
            <div className='add-record-page__header-text-container'>
                Add new finance record
            </div>
        </div>
    );

    return (
        <div className='add-record-page'>
            <Area
                headerContent={headerContent}
            >
                <form className='add-record-page__form' onSubmit={onSubmitHandler}>
                    <TextInput
                        initialValue={description}
                        label='Description'
                        placeholder='Enter description of your record'
                        onValueChange={setDescription}
                    />
                    <TextInput
                        initialValue={amount.toString()}
                        label='Amount'
                        placeholder='Enter amount of money'
                        onValueChange={onAmountChange}
                        type='number'
                    />
                    <TextInput
                        label='Date'
                        initialValue={date}
                        placeholder='Enter date of your record'
                        onValueChange={setDate}
                        type='date'
                    />
                    <div className='add-record-page__submit-button'>
                        <Button
                            variant='dark'
                            text='Add new record'
                            type='submit'
                        />
                    </div>
                </form>
            </Area>
        </div>
    );
};

// UI_Angular/src/app/pages/add-record-page/add-record-page.component.ts
import { Component, OnInit } from "@angular/core";
import { FormControl, FormGroup } from "@angular/forms";
import { Router } from "@angular/router";

import { routesPaths } from "../routes";
import { FinanceRecordsService } from "../../services/finance-records.service";
import { IFinanceRecord } from "../../models/financeRecord";

@Component({
  selector: "app-add-record-page",
  templateUrl: "./add-record-page.component.html",
  styleUrl: "./add-record-page.component.css"
})
export class AddRecordPageComponent implements OnInit {
  financeRecordForm: FormGroup;

  constructor(private router: Router, private financeRecordService: FinanceRecordsService) {}

  ngOnInit(): void {
    const initialDate = new Date().toISOString().split('T')[0];

    this.financeRecordForm = new FormGroup({
      description: new FormControl(""),
      amount: new FormControl(0),
      date: new FormControl(initialDate),
    });
  }

  onSubmitHandler() {
    const newFinanceRecord: IFinanceRecord = {
      ...this.financeRecordForm.value,
      id: crypto.randomUUID(),
      date: new Date(this.financeRecordForm.value.date),
    };

    this.financeRecordService
      .postFinanceRecord(newFinanceRecord)
      .subscribe(() => this.router.navigate([routesPaths.main]));
  }
}

<div class="add-record-page">
  <app-area>
    <div header class="add-record-page__header">
      <div className="add-record-page__header-text-container">
        Add new finance record
      </div>
    </div>
    <form
      content
      class="add-record-page__form"
      [formGroup]="financeRecordForm"
      (ngSubmit)="onSubmitHandler()"
    >
      <app-text-input
        formControlName="description"
        label="Description"
        placeholder="Enter description of your record"
      >
      </app-text-input>
      <app-text-input
        formControlName="amount"
        label="Amount"
        placeholder="Enter amount of money"
        type="number"
      >
      </app-text-input>
      <app-text-input
        formControlName="date"
        label="Date"
        placeholder="Enter date of your record"
        type="date"
      >
      </app-text-input>
      <div class="add-record-page__submit-button">
        <app-button
          variant="dark"
          text="Add new record"
          type="submit">
        </app-button>
      </div>
    </form>
  </app-area>
</div>
