// UI_React/src/app/pages/MainPage/MainPage.tsx
import { useContext } from 'react';

import Area from '../../components/Area';
import Button from '../../components/Button';
import FinanceRecord from '../../components/FinanceRecord';
import { FinanceDataContext } from '../../contexts';
import { RandomFinanceRecordService } from '../../services';

import { dateSortingMethod } from './helpers';

import './MainPage.css';

export const MainPage: React.FC = () => {
    const { totalBalance, financeRecords, addFinanceRecord, removeFinanceRecord } = useContext(FinanceDataContext);

    const addRecord = () => {
        const randomRecord = RandomFinanceRecordService.generateRandomFinanceRecord();
        addFinanceRecord(randomRecord);
    };

    const headerContent = (
        <div className='main-page__header'>
            <div className='main-page__header-text-container'>
                Total balance is: {totalBalance}$
            </div>
            <Button
                variant='dark'
                text='Add random record'
                onClick={addRecord}
            />
        </div>
    );

    const financeRecordsComponents = financeRecords
        .sort(dateSortingMethod)
        .map((record) => {
            return (
                <FinanceRecord
                    key={record.id}
                    record={record}
                    onDelete={removeFinanceRecord}
                />
            );
        });

    return (
        <div className='main-page'>
            <Area
                headerContent={headerContent}
            >
                {financeRecordsComponents}
            </Area>
        </div>
    );
};

// UI_Angular/src/app/pages/main-page/main-page.component.ts
import { Component, OnInit } from "@angular/core";
import { Observable } from "rxjs";

import { IFinanceRecord } from "../../models/financeRecord";
import { FinanceRecordsService } from "../../services/finance-records.service";
import { RandomFinanceRecordService } from "../../services/random-finance-record.service";
import { FinanceRecordsStoreService } from "../../services/state-store/finance-records-store.service";

@Component({
  selector: "app-main-page",
  templateUrl: "./main-page.component.html",
  styleUrl: "./main-page.component.css"
})
export class MainPageComponent implements OnInit {
  totalBalance$: Observable<number>;
  financeRecords$: Observable<IFinanceRecord[]>;

  constructor(
    private financeRecordsStoreService: FinanceRecordsStoreService,
    private financeRecordsService: FinanceRecordsService,
    private randomFinanceRecordService: RandomFinanceRecordService
  ) {
    this.totalBalance$ = this.financeRecordsStoreService.totalBalance$;
    this.financeRecords$ = this.financeRecordsStoreService.financeRecords$;
  }

  ngOnInit(): void {
    this.financeRecordsService
      .getAllFinanceRecords()
      .subscribe((records: IFinanceRecord[]) => {
        this.financeRecordsStoreService.financeRecords = records;
      });
  }

  addRandomRecordClickHandler(event: MouseEvent) {
    const randomRecord = this.randomFinanceRecordService.generateRandomFinanceRecord();

    this.financeRecordsService
      .postFinanceRecord(randomRecord)
      .subscribe(() => {
        this.financeRecordsStoreService.addFinanceRecord(randomRecord);
      });
  }

  deleteRecordClickHandler(recordId: string) {
    this.financeRecordsService
      .deleteFinanceRecord(recordId)
      .subscribe(() => {
        this.financeRecordsStoreService.removeFinanceRecord(recordId);
      });
  }
}

<div class="main-page">
  <app-area>
    <div header class="main-page__header">
      <div class="main-page__header-text-container">
        Total balance is: {{ totalBalance$ | async }}$
      </div>
      <app-button
        variant="dark"
        text="Add random record"
        (onClick)="addRandomRecordClickHandler($event)"
      >
      </app-button>
    </div>
    <div content>
      <app-finance-record
        *ngFor="let record of financeRecords$ | async"
        [record]="record"
        (onDeleteClick)="deleteRecordClickHandler($event)"
      >
      </app-finance-record>
    </div>
  </app-area>
</div>
