// UI_Angular/src/app/components/button/button.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  selector: "app-button",
  templateUrl: "./button.component.html",
  styleUrl: "./button.component.css"
})
export class ButtonComponent {
  @Input() text: string = "Default text";
  @Input() disabled: boolean = false;
  @Input() type: "button" | "submit" = "button";
  @Input() variant: "dark" | "light" = "light";

  @Output() onClick = new EventEmitter<MouseEvent>();

  onButtonClickHandler(event: MouseEvent) {
    this.onClick.emit(event);
  }
}

<button
  class="button"
  [ngClass]="{
    'button--dark' : variant === 'dark',
    'button--light' : variant === 'light'
  }"
  [disabled]="disabled"
  (click)="onButtonClickHandler($event)"
  [type]="type"
>
  {{ text }}
</button>

// UI_React/src/app/components/Button/Button.tsx
import './Button.css';

export interface IButtonProps {
    variant?: 'dark' | 'light';
    disabled?: boolean;
    text?: string;
    onClick?: () => void;
    type?: 'button' | 'submit';
}

export const Button: React.FC<IButtonProps> = ({
    text,
    onClick,
    variant = 'light',
    disabled = false,
    type = 'button'
}) => {
    const variantClassNames = variant === 'dark' ? 'button--dark' : 'button--light';
    const buttonClassNames = `button ${variantClassNames}`;

    return (
        <button
            disabled={disabled}
            onClick={onClick}
            className={buttonClassNames}
            type={type}
        >
            {text}
        </button>
    );
};
