// UI_Angular/src/app/components/finance-record/finance-record.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { IFinanceRecord } from '../../models/financeRecord';

@Component({
  selector: 'app-finance-record',
  templateUrl: './finance-record.component.html',
  styleUrl: './finance-record.component.css'
})
export class FinanceRecordComponent {
  @Input() record: IFinanceRecord = {} as IFinanceRecord;

  @Output() onDeleteClick = new EventEmitter<string>();

  onDeleteClickHandler(event: MouseEvent) {
    this.onDeleteClick.emit(this.record.id);
  }
}

<div
  class="finance-record"
  [ngClass]="{
    'finance-record--positive': record.amount > 0,
    'finance-record--negative': record.amount < 0
  }"
>
  <div class="finance-record__date">
    {{ record.date.toLocaleDateString() }}
  </div>
  <div class="finance-record__description">
    {{ record.description }}
  </div>
  <div class="finance-record__row-end">
    <div class="finance-record__amount">
      {{ record.amount }}$
    </div>
    <span class="finance-record__row-end-divider"></span>
    <div class="finance-record__delete-button">
      <img src="assets/delete.svg" (click)="onDeleteClickHandler($event)" />
    </div>
  </div>
</div>

// UI_React/src/app/components/FinanceRecord/FinanceRecord.tsx
import { IFinanceRecord } from '../../api';

import DeleteSvgIcon from '../../../assets/delete.svg?react';

import './FinanceRecord.css';

export interface IFinanceRecordProps {
    record: IFinanceRecord;
    onDelete: (recordId: string) => void;
}

export const FinanceRecord: React.FC<IFinanceRecordProps> = ({ record, onDelete }) => {
    const deleteHandler = () => onDelete(record.id);

    const recordColorClassName = record.amount > 0 ? 'finance-record--positive' : 'finance-record--negative';
    const recordClassNames = `finance-record ${recordColorClassName}`;

    return (
        <div className={recordClassNames}>
            <div className='finance-record__date'>
                {record.date.toLocaleDateString()}
            </div>
            <div className='finance-record__description'>
                {record.description}
            </div>
            <div className='finance-record__row-end'>
                <div className='finance-record__amount'>
                    {record.amount}$
                </div>
                <span className='finance-record__row-end-divider' />
                <div className='finance-record__delete-button'>
                    <DeleteSvgIcon onClick={deleteHandler}/>
                </div>
            </div>
        </div>
    );
};
