// UI_React/src/app/components/Header/Header.tsx
import ReactSvgIcon from '../../../assets/react.svg?react';
import MoneySvgIcon from '../../../assets/money.svg?react';

import './Header.css';

export const Header: React.FC = () => {
    return (
        <div className='page-header'>
            <MoneySvgIcon className='page-header__icon'/>
            <h1>Finance App. React_UI</h1>
            <ReactSvgIcon  className='page-header__icon'/>
        </div>
    );
};

// UI_Angular/src/app/components/header/header.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrl: "./header.component.css"
})
export class HeaderComponent {

}

<div class="page-header">
  <img class="page-header__icon" src="assets/money.svg"/>
  <h1>Finance App. Angular_UI</h1>
  <img class="page-header__icon" src="assets/angular.svg"/>
</div>
