// UI_React/src/app/components/NavigationMenu/NavigationMenu.tsx
import { useLocation, useNavigate } from 'react-router-dom';

import Button from '../Button';

import { routesPaths } from '../../pages';

import './NavigationMenu.css';

export const NavigationMenu: React.FC = () => {
    const navigate = useNavigate();
    const { pathname: currentPath } = useLocation();

    return (
        <div className='navigation-menu'>
            <div className='navigation-menu__item'>
                <Button
                    text='Main page'
                    onClick={() => navigate(routesPaths.main)}
                    disabled={currentPath === routesPaths.main}
                />
            </div>
            <div className='navigation-menu__item'>
                <Button
                    text='Add new record'
                    onClick={() => navigate(routesPaths.addRecord)}
                    disabled={currentPath === routesPaths.addRecord}
                />
            </div>
        </div>
    );
};

// UI_Angular/src/app/components/navigation-menu/navigation-menu.component.ts
import { Component } from "@angular/core";
import { NavigationEnd, Router } from "@angular/router";
import { filter, map } from "rxjs/operators";

import { routesPaths } from "../../pages/routes";

@Component({
  selector: "app-navigation-menu",
  templateUrl: "./navigation-menu.component.html",
  styleUrl: "./navigation-menu.component.css"
})
export class NavigationMenuComponent {
  currentPath: string = "";
  routesPaths = routesPaths;

  constructor(private router: Router) {
    router.events
      .pipe(
        filter(event => event instanceof NavigationEnd),
        map(event => event as NavigationEnd)
      )
      .subscribe((event: NavigationEnd) => {
        this.currentPath = event.url;
      });
  }

  navigateToMainPage(event: MouseEvent) {
    this.router.navigate([routesPaths.main]);
  }

  navigateToAddRecordPage(event: MouseEvent) {
    this.router.navigate([routesPaths.addRecord]);
  }
}

<div class="navigation-menu">
  <div class="navigation-menu__item">
    <app-button
      text="Main page"
      (onClick)="navigateToMainPage($event)"
      [disabled]="currentPath === routesPaths.main"
    >
    </app-button>
  </div>
  <div class="navigation-menu__item">
    <app-button
      text="Add new record"
      (onClick)="navigateToAddRecordPage($event)"
      [disabled]="currentPath === routesPaths.addRecord"
    >
    </app-button>
  </div>
</div>
