// UI_React/src/app/App.tsx
import { useRoutes } from 'react-router-dom';

import Header from './components/Header';
import Footer from './components/Footer';
import NavigationMenu from './components/NavigationMenu';

import routes from './pages';

import { FinanceDataContextProvider } from './contexts';

import './App.css';

const App: React.FC = () => {
    const definedRoutes = useRoutes(routes);

    return (
        <div className='app__root'>
            <FinanceDataContextProvider>
                <Header />
                <NavigationMenu />
                <div className='app__content'>
                    {definedRoutes}
                </div>
                <Footer />
            </FinanceDataContextProvider>
        </div>
    );
}

export default App;

// UI_Angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css"
})
export class AppComponent { }

﻿<div class="app__root">
  <app-header></app-header>
  <app-navigation-menu></app-navigation-menu>
  <div class="app__content">
    <router-outlet></router-outlet>
  </div>
  <app-footer></app-footer>
</div>
